version: "3.9"

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  pollapp:
    build:
      context: .
      dockerfile: pollapp.Dockerfile
    container_name: pollapp
    depends_on:
      - redis
    environment:
      - APP_REDIS_URL=redis://redis:6379
    ports:
      - "8080:8080"
    restart: always

#  frontend:
#    build:
#      context: .
#      dockerfile: frontend.Dockerfile # nginx Vue bundle
#    container_name: poll-frontend
#    ports:
#      - "80:80"
#    depends_on:
#      - pollapp
#    restart: always
